"""The job types an appliance operation may claim, and the states it moves through."""

from __future__ import annotations


ALLOWED_JOB_TYPES = {
    "application.research",
    "compose.draft",
    "compose.install",
    "compose.import",
    "compose.backup",
    "compose.validate",
    "compose.pull",
    "compose.deploy",
    "compose.stop",
    "compose.start",
    "compose.restart",
    "compose.update",
    "managed.remove",
    "model.inspect",
    "model.download",
    "model.deploy",
    "model.install_release",
    "agent.deploy",
    "checkpoint.restore",
    "system.update.stage",
    "system.update.apply",
    "appliance.factory-reset",
    "appliance.portable-import",
    "appliance.upgrade",
    "host.vnc.enable",
    "host.docker.install",
    "host.memory.optimize",
    "host.web-research.manage",
    "cluster.initialize",
    "cluster.node.join",
    "cluster.node.availability",
    "cluster.node.remove",
    "cluster.app.deploy",
    "cluster.service.backup",
    "cluster.service.configure",
    "cluster.service.manage",
    "cluster.service.remove",
    "cluster.service.restore",
    "cluster.pooled.remove",
    "cluster.llm.deploy",
}
JOB_STATES = {
    "queued",
    "validating",
    "downloading",
    "running",
    "waiting",
    "needs_approval",
    "paused",
    "rejected",
    "superseded",
    "starting",
    "healthy",
    "failed",
    "cancelling",
    "cancelled",
    "completed",
}
ACTIVE_JOB_STATES = {
    "validating",
    "downloading",
    "starting",
    "running",
    "cancelling",
}
TERMINAL_JOB_STATES = {
    "completed", "healthy", "failed", "rejected", "cancelled", "superseded",
}
