"""The LLM Server auth PROXY: a Vaelor-controlled LAN gate over a loopback model.

**Why a proxy, not engine-level auth (the live-proven pivot).** The GPU AI-Chat
model is served by ``llama-server`` in a container that binds LOOPBACK ONLY
(:mod:`vaelor.gpu_rocmfpx_service` publishes it on ``127.0.0.1:<model-port>`` and
never passes an api key to the engine). Engine-level auth was tried and could not
be trusted: the ROCmFP4 fork's ``llama-server`` does NOT enforce
``--api-key``/``--api-key-file``/``LLAMA_API_KEY`` at all, so a keyed LAN bind was
an UNAUTHENTICATED LAN endpoint. A Vaelor-controlled proxy is the only trustworthy
LAN gate, and it is engine-agnostic: a fork OR a mainline model is exposed
identically and safely, because neither is ever LAN-published.

**The gate.** When the LLM Server is ENABLED, Vaelor runs one small ``nginx``
container in front of the model's loopback endpoint:

* the container is launched by the root hardware bridge (``proxy_start`` /
  ``proxy_stop`` / ``proxy_status``), the same privileged account that launches the
  model container;
* it runs with ``--network host`` so it shares the host network namespace: its
  ``listen`` binds the host's LAN address:port directly, and ``proxy_pass`` reaches
  the model on ``127.0.0.1:<model-port>`` (host loopback). ``--network host`` is
  the approach that WORKS with the model published on ``127.0.0.1``: a model bound
  to loopback is NOT on the docker bridge, so ``--add-host``/``host-gateway`` (which
  resolves to the bridge gateway, e.g. ``172.17.0.1``) could not reach it;
* the config (generated by Vaelor with the current key, written root-owned and
  mounted READ-ONLY) enforces ``Authorization: Bearer <key>``: any request whose
  Authorization header is not exactly ``Bearer <key>`` gets 401, except ``/health``
  (unauthenticated, proxied so it reflects the model). The key lives in the config
  FILE, never on any argv (``docker inspect`` / ``/proc`` are readable to local
  accounts). Buffering is off and the read/send timeouts are long so OpenAI SSE
  streaming works.

**The invariant, now airtight and engine-agnostic.** There is NO way to expose the
model on the LAN except through the running auth proxy, which always has the key:
:func:`_require_keys` refuses to build a proxy launch without a key, and the model
container never binds non-loopback. So enable/disable/rotate all reduce to
starting, stopping, or re-keying this one container.

**The same gate, on a worker (VD-129, the amendment).** A replicated
deployment's worker runs its vLLM replica on loopback and the SAME nginx image
in front of it as :func:`render_gate_config`: the cluster address on the
replica port, the same Bearer check (:func:`bearer_check`, rendered once for
both configs), ``/v1/`` and ``/health`` forwarded to loopback and everything
else answered 404 - because vLLM's own ``--api-key`` was live-probed to gate
only ``/v1`` and leave ``/invocations``, ``/tokenize`` and ``/metrics`` open.
That config is rendered by `GpuPoolRuntime.start_gate` and shipped to the
worker over its transport as a root ``0600`` file; the container is a systemd
unit's foreground process there rather than a bridge-launched daemon, which is
the one difference :func:`proxy_container_command` carries.

**The usage log (ACC-043, ACC-048).** A LAN client's request never passes
through a Vaelor process, so the gate is the one place that can say which key
was used and when. The LLM Server proxy's config (and only that one - the
worker gate, the agent gate and the balancer render none) writes one line per
ADMITTED request into :data:`vaelor.llm_gate_usage.GATE_LOG_FILENAME`, naming
the key by its vault FINGERPRINT, which the config sets inside the branch that
matched that key. The Authorization header is never logged, and a refused
request writes nothing. The directory is a root ``0755`` one under
``/run/vaelor`` that the bridge prepares and refuses to use when it is a link or
not its own (then the gate still serves, without the log, and its status says
so); the bridge rotates the file on its own timer (:mod:`vaelor.llm_gate_log`).
A refused request is written to a separate, separately capped file, so guessing
at keys stays visible and a flood of refusals can never push an admitted line
out of the key log. The control plane reads both (:mod:`vaelor.llm_gate_usage`).
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any, Callable, List, Mapping, Optional, Sequence

from .flm_service import _validate_port
#: The configs these containers run are rendered in `llm_gate_config`; every
#: name is re-exported here, where its callers and tests have always found it.
from .llm_gate_config import (  # noqa: F401 - re-exported
    MODEL_LOOPBACK_HOST,
    STREAMING_DIRECTIVES,
    _require_keys,
    _validate_bind_host,
    bearer_check,
    render_gate_config,
    render_proxy_config,
    render_unloaded_config,
    replica_locations,
    validate_api_key,
)
from .llm_gate_log import GateLogRotator, LogDirFs, prepare_log_dir
from .llm_gate_usage import GATE_LOG_CONTAINER_DIR, GATE_LOG_DIRNAME
from .llm_server_state import applied_marker, key_fingerprint, serve_binding
from .llm_server_wake import WAKE_SOCKET_DIR, WAKE_SOCKET_MOUNT, wake_socket_refusal
from .runtime_paths import run_path

LOGGER = logging.getLogger(__name__)


#: The LAN port the proxy listens on, and the port an external OpenAI client
#: targets (``http://<lan>:<this>/v1``). Fixed so the advertised base URL is
#: stable across reboots and redeploys. Chosen OUTSIDE the model server's loopback
#: allocation range (8080-8099, :func:`vaelor.executor_network.available_model_port`)
#: so the proxy's ``0.0.0.0:<port>`` bind can never collide with the model's
#: ``127.0.0.1:<model-port>`` bind, and outside the reserved control-plane ports.
LLM_SERVER_PROXY_PORT = 11434

#: What the gate fronts, as its status names it: the model's loopback port;
#: (ACC-058, review S2) the control plane's wake responder on its unix socket;
#: or (VD-159) nothing - the door answers "not loaded" for itself while the
#: cluster model is unloaded and no request can wake it. An explicit word
#: carried in its own field - never a sentinel port.
UPSTREAM_MODEL = "model"
UPSTREAM_WAKE_DOOR = "wake-door"
UPSTREAM_UNLOADED_NOTICE = "unloaded-notice"


def door_upstream(*, wake_door: bool = False, unloaded_notice: bool = False) -> str:
    """The one word for what a door fronts, from the two markers a caller passes.

    The markers are separate arguments because each crossed the bridge as its
    own payload key; they name mutually exclusive doors, so both is refused
    here, once, for the process and the controller alike.
    """
    if wake_door and unloaded_notice:
        raise ValueError("An LLM Server door fronts the wake responder or nothing, not both.")
    if wake_door:
        return UPSTREAM_WAKE_DOOR
    return UPSTREAM_UNLOADED_NOTICE if unloaded_notice else UPSTREAM_MODEL

#: The nginx image the proxy runs. ``stable-alpine`` is small and already present
#: on the Z2; the proxy needs nothing but a stock nginx.
#:
#: **Pinned by DIGEST**, in the ``name:tag@sha256:`` form docker accepts for
#: ``pull``/``run``/``image inspect`` alike, for the reason the model images are
#: (:data:`vaelor.gpu_rocmfpx_service.GPU_CONTAINER_IMAGE`): ``stable-alpine`` is a
#: moving tag, and this container is the AUTHENTICATED DOOR in front of a keyless
#: loopback model - the one place where "whatever the registry served that day" is
#: least acceptable. **Measured 0.03 GB on the appliance, 2026-09-05. To re-pin:**
#: ``docker pull nginx:stable-alpine``, then ``docker image inspect --format
#: '{{index .RepoDigests 0}}' nginx:stable-alpine`` for the digest and ``docker
#: image ls`` for the size - and update the figure in ``deploy/install-vaelor.sh``'s
#: pre-pull disk preflight, which is sized from it.
PROXY_IMAGE = (
    "nginx:stable-alpine"
    "@sha256:97d490c12ba55b4946b01546d1c3ed324e8d41ab1c9fcb2a616aa470620e5b46"
)

#: The fixed name of the single auth-proxy container, so ``stop``/``status`` can
#: address it without tracking an id across the bridge boundary (mirrors
#: :data:`vaelor.gpu_rocmfpx_service.GPU_CONTAINER_NAME`).
PROXY_CONTAINER_NAME = "vaelor-llm-proxy"

#: Where the generated nginx config is written on the HOST (root-owned ``0600``,
#: because it carries the plaintext key) and mounted READ-ONLY into the container.
#: Removed when the proxy is stopped, so a disabled server leaves no key behind.
#: Lives under ``/run/vaelor`` (tmpfs), NOT the state root: the root hardware
#: bridge that launches the proxy runs under ``ProtectSystem=strict`` with
#: ``/var/lib/vaelor`` read-only, so a config there fails with EROFS (live-caught);
#: ``/run/vaelor`` is in the bridge's ReadWritePaths. Ephemeral is correct - the
#: config is regenerated from the persisted state on every ``proxy_start``.
PROXY_CONFIG_HOST_FILE = run_path("llm-server-proxy.conf")

#: Where the config is mounted inside the container. nginx's stock ``nginx.conf``
#: includes ``/etc/nginx/conf.d/*.conf`` from within its ``http`` block, so
#: replacing the image's ``default.conf`` with our server block is all that is
#: needed - no custom ``nginx.conf``.
PROXY_CONFIG_CONTAINER_FILE = "/etc/nginx/conf.d/default.conf"

#: Bounds on the docker calls, mirroring the model launch's.
DOCKER_RUN_TIMEOUT = 120
DOCKER_PULL_TIMEOUT = 600
DOCKER_QUERY_TIMEOUT = 30

#: How long ``docker stop`` may drain nginx before SIGKILL. nginx exits promptly.
STOP_GRACE_SECONDS = 5


class ProxyImageMissingError(FileNotFoundError):
    """The nginx image is not present and could not be pulled.

    A subclass of ``FileNotFoundError`` (hence ``OSError``) so a caller's fall-back
    set catches it like the model image-missing error.
    """


def proxy_container_command(
    *,
    listen_port: int = LLM_SERVER_PROXY_PORT,
    api_keys: Sequence[str],
    docker: str = "docker",
    image: str = PROXY_IMAGE,
    container_name: str = PROXY_CONTAINER_NAME,
    config_host_file: str = PROXY_CONFIG_HOST_FILE,
    config_container_file: str = PROXY_CONFIG_CONTAINER_FILE,
    foreground: bool = False,
    log_dir: str = "",
    wake_door: bool = False,
) -> List[str]:
    """The ``docker run -d`` argv for the auth proxy container.

    ::

        docker run -d --name vaelor-llm-proxy --network host
            -v <config-host>:/etc/nginx/conf.d/default.conf:ro <image>

    ``--network host`` shares the host netns so nginx's ``listen`` binds the LAN
    interface and ``proxy_pass`` reaches the loopback model (see the module
    docstring for why ``host-gateway`` would not). The bind address and port live in
    the mounted CONFIG, not on ``-p``, and the key lives in that config too - so the
    plaintext key is NOWHERE on the argv. :func:`_require_keys` refuses to build this
    without a key: a proxy is meaningless (and unsafe) without one. A list, never a
    string, so no element can be split or chained by a shell.

    ``foreground`` trades ``-d`` for ``--rm``: the container is a systemd
    unit's main process - a worker's replica gate (VD-129), supervised by
    ``Restart=on-failure`` as the vLLM units are - rather than a daemon the
    root bridge inspects by name. Everything else is the same argv, so the
    two gates the product runs cannot drift on how nginx is launched.

    ``log_dir`` mounts the usage-log directory (the LLM Server proxy only);
    ``wake_door`` adds the control plane's wake folder, read-only - the one
    extra mount, fixed, and only for the LLM Server's idle-unloaded door.
    Neither set, the argv is exactly what it was before either existed.
    """
    _require_keys(api_keys)
    _validate_port(listen_port)
    mounts = ["-v", "{}:{}:ro".format(config_host_file, config_container_file)]
    if log_dir:
        mounts += ["-v", "{}:{}".format(log_dir, GATE_LOG_CONTAINER_DIR)]
    if wake_door:
        mounts += ["-v", "{}:{}:ro".format(WAKE_SOCKET_DIR, WAKE_SOCKET_MOUNT)]
    return [
        docker, "run", "--rm" if foreground else "-d", "--name", container_name,
        "--network", "host", *mounts, image,
    ]


def write_proxy_config(path: str, content: str) -> None:
    """Write ``content`` root-owned ``0600``, or REMOVE the file when it is empty.

    The config carries the plaintext key, so it is created with mode ``0o600`` via
    ``O_CREAT`` rather than written then chmod'd (never briefly world-readable), and
    an empty ``content`` unlinks any stale config so a stopped/disabled proxy leaves
    nothing readable behind. Written root-side by :meth:`LlmServerProxyProcess.start`
    (the bridge launches as root).

    ``O_NOFOLLOW`` is set so that if a symlink has been PLANTED at ``path`` the open
    FAILS rather than following it: these configs live under ``/run/vaelor``, a
    group-writable tmpfs an in-group process could seed with a symlink, and without
    this flag a root writer would then be steered into writing the key-bearing
    ``content`` to (or, with a following chown, handing ownership of) an
    attacker-chosen target such as a systemd unit - a root-write primitive. A
    legitimate redeploy overwrites a REGULAR file, which ``O_NOFOLLOW`` permits;
    only a symlink is refused. (``getattr`` keeps it a no-op on a non-POSIX host,
    where the flag does not exist and there are no such symlinks to follow.)
    """
    target = Path(path)
    if not content:
        try:
            target.unlink()
        except OSError:
            pass
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(str(target), flags, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(content)
    try:
        os.chmod(target, 0o600)
    except OSError:
        pass


def _default_run(command: Sequence[str], *, timeout: Optional[int] = None):
    """Run a docker command, capturing output, never raising on non-zero.

    stdout/stderr are captured (not DEVNULL): a ``docker run`` that fails explains
    itself on stderr, which the caller surfaces in the raised error (LESSONS 8).
    """
    return subprocess.run(
        list(command), capture_output=True, text=True, check=False, timeout=timeout
    )


def _lifecycle(method):
    """Mark a proxy start or stop as in flight, so the log rotator stands aside."""
    def wrapper(self, *args, **kwargs):
        self._in_flight += 1
        try:
            return method(self, *args, **kwargs)
        finally:
            self._in_flight -= 1

    wrapper.__name__ = method.__name__
    wrapper.__doc__ = method.__doc__
    return wrapper


class LlmServerProxyProcess:
    """A supervised nginx auth-proxy CONTAINER, launched and stopped root-side.

    The proxy analogue of :class:`vaelor.gpu_rocmfpx_service.GpuServerProcess`: it
    manages a ``docker run -d`` nginx container in front of the loopback model,
    generating the keyed config each launch and mounting it read-only. Same
    ``start``/``stop``/``alive``/``status`` shape, and the docker calls go through
    an injected ``run`` seam so the launch is verifiable without docker or a GPU.
    """

    def __init__(
        self,
        *,
        run: Optional[Callable[..., Any]] = None,
        docker: Optional[str] = None,
        image: str = PROXY_IMAGE,
        container_name: str = PROXY_CONTAINER_NAME,
        config_host_file: str = PROXY_CONFIG_HOST_FILE,
        config_container_file: str = PROXY_CONFIG_CONTAINER_FILE,
        usage_log_dir: Optional[str] = None,
        log_dir_fs: Optional[LogDirFs] = None,
    ):
        self._run = run or _default_run
        self._docker = docker
        self._image = image
        self._name = container_name
        self._config_host_file = config_host_file
        self._config_container_file = config_container_file
        # The usage log lives beside the config: for the shipping proxy that is
        # `llm_gate_usage.GATE_LOG_HOST_DIR`, the directory the control plane reads.
        self._usage_log_dir = usage_log_dir or os.path.join(
            os.path.dirname(config_host_file), GATE_LOG_DIRNAME
        )
        # Whether the RUNNING gate writes the usage log, and why not when it
        # does not - reported by `status`, so "no use recorded" is never read
        # off a gate that was not recording.
        self.usage_log = False
        self._dir_reason = ""
        self._log_dir_fs = log_dir_fs
        self._in_flight = 0
        self.rotator = GateLogRotator(
            self._usage_log_dir, container=container_name, docker=self._docker_binary,
            run=self._run, busy=lambda: self._in_flight > 0,
        )
        self.listen_host = ""
        self.listen_port = 0
        self.model_port = 0
        self.upstream = UPSTREAM_MODEL
        # The SET-hash of the keys rendered into the RUNNING gate's config -
        # the gate's own truth, reported by `status` so a caller compares what
        # is running, not what it last asked for. Never a key: a hash of the
        # per-key fingerprints, the applied-binding marker's basis.
        self.key_set = ""

    def _docker_binary(self) -> str:
        return self._docker or shutil.which("docker") or "/usr/bin/docker"

    def ensure_image(self, docker: Optional[str] = None) -> None:
        """Make sure the nginx image is present, pulling it once if not.

        ``docker image inspect`` is the cheap presence probe; only a miss triggers a
        ``docker pull``. On the Z2 the image is already pulled (a fast no-op); a
        failed fetch raises :class:`ProxyImageMissingError` naming it.
        """
        docker = docker or self._docker_binary()
        inspected = self._run(
            [docker, "image", "inspect", self._image], timeout=DOCKER_QUERY_TIMEOUT
        )
        if getattr(inspected, "returncode", 1) == 0:
            return
        pulled = self._run([docker, "pull", self._image], timeout=DOCKER_PULL_TIMEOUT)
        if getattr(pulled, "returncode", 1) != 0:
            raise ProxyImageMissingError(
                "The LLM Server proxy image {} is not present and could not be "
                "pulled: {}".format(
                    self._image, (getattr(pulled, "stderr", "") or "").strip()
                )
            )

    #: What this container is called in its own failure sentence. The replica
    #: balancer (`gpu_pool_replicas.BalancerProcess`) is the same launch with
    #: another config and another name, and must not fail as "the LLM Server
    #: proxy" (LESSONS pattern 5).
    label = "LLM Server proxy"

    @_lifecycle
    def start(
        self, *, listen_host: str, listen_port: int, model_port: Optional[int],
        api_keys: Sequence[str], wake_door: bool = False,
        unloaded_notice: bool = False, loading: bool = False,
    ) -> dict:
        """Validate, generate the keyed config, then launch the proxy container.

        A running proxy is replaced first. The key/coupling and every validation
        happen while rendering the config, BEFORE the previous container is touched,
        so a keyless or malformed request cannot take down a healthy gate. The
        config is landed (root ``0600``) after the argv validates and after the old
        container is removed, and is mounted read-only into the container. The gate
        accepts ANY of ``api_keys`` (F3b-ii): the LLM Server is now multi-key.

        The usage log is prepared only after the request has validated, and a
        directory that cannot be used never costs the gate: it is launched
        without the log and :attr:`usage_log_reason` says why.

        ``unloaded_notice`` (VD-159) launches the door that answers for itself
        while the cluster model is unloaded: no model port, no extra mount.
        With ``loading`` it says the model is loading instead (ACC-193).
        """
        fronts = door_upstream(wake_door=wake_door, unloaded_notice=unloaded_notice)

        def render(usage_log: bool) -> str:
            return render_proxy_config(
                listen_host=listen_host, listen_port=listen_port,
                model_port=model_port, api_keys=api_keys, usage_log=usage_log,
                wake_door=wake_door, unloaded_notice=unloaded_notice, loading=loading,
            )

        render(False)
        if wake_door:
            # Root is about to mount a folder a service account made: only the
            # control plane's own, holding its own socket (review S2).
            refusal = wake_socket_refusal()
            if refusal is not None:
                raise RuntimeError(refusal)
        log_dir, self._dir_reason = prepare_log_dir(self._usage_log_dir, self._log_dir_fs)
        if self._dir_reason:
            LOGGER.warning("%s", self._dir_reason)
        config = render(bool(log_dir))
        self._launch(
            config, listen_port=int(listen_port), api_keys=api_keys, log_dir=log_dir,
            wake_door=wake_door,
        )
        self.usage_log = bool(log_dir)
        if self.usage_log:
            self.rotator.start()
        self.listen_host = _validate_bind_host(listen_host)
        self.listen_port = _validate_port(listen_port)
        self.model_port = (
            _validate_port(model_port) if fronts == UPSTREAM_MODEL else 0
        )
        self.upstream = fronts
        self.key_set = applied_marker(True, api_keys).key_fingerprint
        return self.status()

    @property
    def usage_log_reason(self) -> str:
        """Why the running gate is not recording use, or cannot keep its log bounded."""
        return self._dir_reason or self.rotator.reason

    def _launch(
        self, config: str, *, listen_port: int, api_keys: Sequence[str],
        log_dir: str = "", wake_door: bool = False,
    ) -> None:
        """Replace the container with one running ``config``: the one launch.

        Shared with the replica balancer, which renders its own config and
        keeps its own binding facts but launches, replaces, mounts and fails
        exactly as the proxy does - the key/coupling included, since
        `proxy_container_command` refuses to build without a key.
        """
        command = proxy_container_command(
            listen_port=int(listen_port), api_keys=api_keys,
            docker=self._docker_binary(), image=self._image,
            container_name=self._name, config_host_file=self._config_host_file,
            config_container_file=self._config_container_file, log_dir=log_dir,
            wake_door=wake_door,
        )
        docker = self._docker_binary()
        self.ensure_image(docker)
        if self.alive():
            self.stop()
        else:
            self._run([docker, "rm", "-f", self._name], timeout=DOCKER_QUERY_TIMEOUT)
        write_proxy_config(self._config_host_file, config)
        result = self._run(command, timeout=DOCKER_RUN_TIMEOUT)
        if getattr(result, "returncode", 1) != 0:
            raise RuntimeError(
                "The {} container could not be started: {}".format(
                    self.label, (getattr(result, "stderr", "") or "").strip()
                )
            )

    def alive(self) -> bool:
        """Whether our proxy container exists and is running, per ``docker inspect``."""
        docker = self._docker_binary()
        try:
            result = self._run(
                [docker, "inspect", "-f", "{{.State.Running}}", self._name],
                timeout=DOCKER_QUERY_TIMEOUT,
            )
        except (OSError, subprocess.SubprocessError):
            return False
        return (
            getattr(result, "returncode", 1) == 0
            and (getattr(result, "stdout", "") or "").strip() == "true"
        )

    @_lifecycle
    def stop(self, *, grace_seconds: int = STOP_GRACE_SECONDS) -> dict:
        """``docker stop`` then ``docker rm``, and REMOVE the key-bearing config.

        Best-effort so a stop never raises; the fixed name is freed and the config
        file unlinked, so a disabled proxy leaves no readable key behind.
        """
        docker = self._docker_binary()
        was_running = self.alive()
        try:
            self._run(
                [docker, "stop", "--time", str(int(grace_seconds)), self._name],
                timeout=DOCKER_RUN_TIMEOUT,
            )
            self._run([docker, "rm", "-f", self._name], timeout=DOCKER_QUERY_TIMEOUT)
        except (OSError, subprocess.SubprocessError):
            pass
        write_proxy_config(self._config_host_file, "")
        self.key_set = ""
        self.usage_log = False
        self.rotator.stop()
        return {"stopped": True, "was_running": was_running}

    def status(self) -> dict:
        """The running gate's facts, including whether it is recording use.

        A read only: the usage log is kept bounded by :attr:`rotator`, the
        bridge's own timer, never here, so a status call cannot fail on it.
        """
        running = self.alive()
        return {
            "running": running,
            "listen_host": self.listen_host,
            "listen_port": self.listen_port,
            "model_port": self.model_port,
            "upstream": getattr(self, "upstream", UPSTREAM_MODEL),
            "key_set": self.key_set,
            "container": self._name,
            "usage_log": self.usage_log,
            "usage_log_reason": self.usage_log_reason,
        }


class LlmServerProxyController:
    """Converge the auth proxy to the persisted LLM Server state, over the bridge.

    The executor-side seam the deploy, the ``llm_server.apply`` job and the
    failure-watch reconcile all drive. It holds a bridge-client-like object with
    ``proxy_start``/``proxy_stop``/``proxy_status`` (production: the root
    :class:`vaelor.hardware_bridge.HardwareBridgeClient`; a test: a recording fake)
    and turns a ``(settings, model_port)`` pair into the one right call:

    * ENABLED with a key -> ``proxy_start`` the keyed gate in front of the model's
      loopback port, listening on the LAN;
    * DISABLED (or a key-less record) -> :meth:`stop`: ``proxy_stop`` and remove it.

    The listen host and key come from :func:`vaelor.llm_server_state.serve_binding`,
    the same derivation the applied-binding marker uses, so the running proxy and
    the marker can never disagree about what "enabled" means.

    :meth:`stop` is also a verb of its own, because the GPU cluster mode switch
    takes the LAN gate down on the way into Mode B and on the way out of it
    without changing the persisted record - the flag is the restore contract,
    and the gate is re-converged from it on `repoint`. The switch's first live
    run (VD-127, 2026-09-05) died on this class NOT having it: every test double
    for the controller had a ``stop`` and the shipping class had only ``apply``,
    so the first controller-led deploy raised ``AttributeError`` out of the
    executor. `apply` reduces a disabled record to the same method, so "stop
    the proxy" has one spelling here.

    :meth:`converged` is the other half of that lesson. `apply` always replaces
    the container (`LlmServerProxyProcess.start` stops the old one first), so a
    caller that applies on every pass takes the LAN gate down for about a
    second each time - the second live run (VD-127, 2026-09-05) found the Mode
    B reconcile doing exactly that every 30 s, ``docker ps`` never showing the
    proxy older than its pass. "Is the proxy already right?" is decided here,
    from the live status, once, for both the Mode A failure-watch and the Mode
    B reconcile; neither carries its own reading of the status.
    """

    def __init__(
        self, client: Any, *, listen_port: int = LLM_SERVER_PROXY_PORT
    ):
        self._client = client
        self._listen_port = listen_port

    def apply(
        self, enabled: bool, api_keys: Any, model_port: int, *, wake_door: bool = False,
        unloaded_notice: bool = False, loading: bool = False,
    ) -> dict:
        """Start the keyed gate - in front of the model, the wake door, or
        nothing (the unloaded door, VD-159; the loading door, ACC-193) - or stop it."""
        fronts = door_upstream(wake_door=wake_door, unloaded_notice=unloaded_notice)
        listen_host, keys = serve_binding(enabled, api_keys)
        if keys and fronts == UPSTREAM_WAKE_DOOR:
            return self._client.proxy_start(
                listen_host, self._listen_port, None, keys, wake_door=True
            )
        if keys and fronts == UPSTREAM_UNLOADED_NOTICE and loading:
            return self._client.proxy_start(
                listen_host, self._listen_port, None, keys, unloaded_notice=True,
                loading=True,
            )
        if keys and fronts == UPSTREAM_UNLOADED_NOTICE:
            return self._client.proxy_start(
                listen_host, self._listen_port, None, keys, unloaded_notice=True
            )
        if keys:
            return self._client.proxy_start(
                listen_host, self._listen_port, int(model_port), keys
            )
        return self.stop()

    def converged(
        self, enabled: bool, fingerprints: Any, model_port: int, *,
        marker_ok: bool = True, wake_door: bool = False,
        unloaded_notice: bool = False,
    ) -> bool:
        """Whether the LIVE proxy already matches ``(enabled, key set, model_port)``.

        ``fingerprints`` is the broker's per-key fingerprint set (its
        ``list()``, no decrypt). Enabled with a non-empty set: running, on this
        listen host and port, fronting ``model_port``, AND carrying that key
        set - read off the status's ``key_set``, the SET-hash the bridge
        rendered into the running gate's config. That is the gate's truth: the
        applied-binding marker records what a caller last ASKED for, and a
        start that timed out on the client while completing on the bridge
        after a later one left the marker naming the new set over a gate still
        admitting a revoked key (2026-09-28 review). ``marker_ok`` is consulted
        only for a status that reports no ``key_set`` at all (a bridge older
        than the field). Disabled or an empty set: not running. Fail-safe: a
        status that cannot be read is "not converged", so the caller applies
        rather than trusts.
        """
        wanted = door_upstream(wake_door=wake_door, unloaded_notice=unloaded_notice)
        listen_host, keys = serve_binding(enabled, fingerprints)
        try:
            status = self.status()
        except Exception:  # noqa: BLE001 - an unreadable gate is an unconverged one
            return False
        running = bool(status.get("running"))
        if not keys:
            return not running
        # What it fronts is its own field (a status without it predates the
        # wake door, so it fronts the model); the model port only matters there.
        fronts = str(status.get("upstream") or UPSTREAM_MODEL)
        bound = (
            running
            and str(status.get("listen_host") or "") == listen_host
            and _port_or_zero(status.get("listen_port")) == int(self._listen_port)
            and fronts == wanted
            and (
                wanted != UPSTREAM_MODEL
                or _port_or_zero(status.get("model_port")) == int(model_port)
            )
        )
        if "key_set" not in status:
            return bound and bool(marker_ok)
        return bound and str(status.get("key_set") or "") == key_fingerprint(keys)

    def stop(self) -> dict:
        """Take the LAN gate down and remove its key-bearing config, over the bridge."""
        return self._client.proxy_stop()

    def status(self) -> Mapping[str, Any]:
        return self._client.proxy_status()


def _port_or_zero(value: Any) -> int:
    """A status field as a port, or 0 for anything a port cannot be read from."""
    try:
        return int(value or 0)
    except (TypeError, ValueError):
        return 0
