import { apiRequest } from "./api";
import type { AgentRuntime } from "./agentRuntimeStatus";
import type { EndpointKey } from "./endpoints";

/**
 * Deployed cluster agents (F6c): the typed data behind the Deployments tab's
 * "Agents" filter and the agent cards under its "Models" filter. An agent is a
 * model backend plus its tools and skills, placed on the cluster and reachable
 * behind its own inbound gate.
 *
 * The honesty rule the backend enforces is carried here: an agent row never
 * holds a secret. `api_key_id` is the id of a stored inbound key, never its
 * value, and `keys` are fingerprint-only profiles. Every field is read
 * defensively so a slightly older or partial backend never blanks the whole
 * surface - and never reads as healthier than it is: a missing `runtime` stays
 * missing (the badge then refuses to say "Serving"), and missing `keys_known`
 * means the keys are NOT known.
 */

/** What an agent's replies are generated by: a backing cluster model deployment,
 *  named the way the Deployments list already names a model row. Never a key. */
export interface AgentBacking {
  model_deployment_name: string;
}

/** Where a deployed agent runs. It sits on the head controller behind its
 *  inbound gate, so `runs_on` is the controller placement id. */
export interface AgentPlacement {
  runs_on: string;
}

/** One deployed cluster agent, exactly as `GET /cluster/agents` returns it. */
export interface AgentDeployment {
  name: string;
  /** The deploy row's stored state. Not what the agent is doing - see `runtime`. */
  state: string;
  endpoint: string;
  backing: AgentBacking;
  custom_agent_id: string;
  custom_agent_version: number | null;
  api_key_id: string;
  /** The canonical broker endpoint id the key routes address (``agent:<id>``). */
  endpoint_id: string;
  placement: AgentPlacement;
  created_at: number | null;
  updated_at: number | null;
  /** The endpoint's ACTIVE keys from the broker (fingerprint-only). */
  keys: EndpointKey[];
  /** False when the broker could not answer: `keys` is then empty and means "unknown". */
  keys_known: boolean;
  /** What the agent is actually doing, or null from a backend older than this reading. */
  runtime: AgentRuntime | null;
}

/** The wire shape of `GET /cluster/agents`. */
interface AgentsSurface {
  agents?: unknown;
}

function asString(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function asNumberOrNull(value: unknown): number | null {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" ? (value as Record<string, unknown>) : {};
}

/** Coerce the backing object, degrading a missing model name to an empty
 *  string rather than throwing, so the row can say "backing not recorded". */
function normalizeBacking(value: unknown): AgentBacking {
  return { model_deployment_name: asString(asRecord(value).model_deployment_name) };
}

/** One fingerprint-only key profile. A row without a credential id cannot be
 *  addressed by rotate or revoke, so it is dropped rather than shown. */
function normalizeKey(value: unknown): EndpointKey | null {
  const record = asRecord(value);
  const credentialId = asString(record.credential_id);
  if (!credentialId) return null;
  return {
    credential_id: credentialId,
    label: asString(record.label),
    key_fingerprint: asString(record.key_fingerprint),
    last4: asString(record.last4),
    created_at: asNumberOrNull(record.created_at),
    last_used_at: asNumberOrNull(record.last_used_at),
  };
}

/** The runtime reading, or null when the backend sent none (never invented). */
function normalizeRuntime(value: unknown): AgentRuntime | null {
  if (!value || typeof value !== "object") return null;
  const record = asRecord(value);
  return {
    state: asString(record.state) || "unknown",
    reason: asString(record.reason),
    detail: asString(record.detail),
  };
}

/**
 * Coerce one agent object into the {@link AgentDeployment} the surfaces render.
 * A missing or wrong-typed field degrades to an empty default rather than
 * throwing, mirroring the MCP catalog's defensive read (`mcpCatalog.ts`).
 */
export function normalizeAgent(value: unknown): AgentDeployment {
  const record = asRecord(value);
  const placement = asRecord(record.placement);
  const keysKnown = record.keys_known === true && Array.isArray(record.keys);
  return {
    name: asString(record.name),
    state: asString(record.state),
    endpoint: asString(record.endpoint),
    backing: normalizeBacking(record.backing),
    custom_agent_id: asString(record.custom_agent_id),
    custom_agent_version: asNumberOrNull(record.custom_agent_version),
    api_key_id: asString(record.api_key_id),
    endpoint_id: asString(record.endpoint_id),
    placement: { runs_on: asString(placement.runs_on) },
    created_at: asNumberOrNull(record.created_at),
    updated_at: asNumberOrNull(record.updated_at),
    keys: keysKnown
      ? (record.keys as unknown[]).map(normalizeKey).filter((key): key is EndpointKey => key !== null)
      : [],
    keys_known: keysKnown,
    runtime: normalizeRuntime(record.runtime),
  };
}

/**
 * Read the deployed cluster agents. Returns an empty list when none are
 * deployed, and is abortable so a surface that leaves the tab never lands a
 * stale answer. A failed read REJECTS: an unreadable list is not an empty one,
 * and each caller says so in its own place.
 */
export async function listClusterAgents(signal?: AbortSignal): Promise<AgentDeployment[]> {
  const surface = await apiRequest<AgentsSurface>("/cluster/agents", { signal });
  return Array.isArray(surface.agents) ? surface.agents.map(normalizeAgent) : [];
}

/** What happened to one attached skill's guidance in the deploy review. */
export type SkillGuidanceStatus = "sent" | "shortened" | "not-sent";

export interface SkillGuidanceRow {
  skill_id: string;
  name: string;
  status: SkillGuidanceStatus;
  reason: string;
  sent_chars: number;
  total_chars: number;
  scopes: string[];
}

export interface SkillRefusal {
  skill_id: string;
  reason: string;
}

export interface SkillLimits {
  skills: number;
  instructions_per_skill: number;
  block: number;
}

/** The limits the deploy applies, used until a preview reports its own. */
export const DEFAULT_SKILL_LIMITS: SkillLimits = { skills: 8, instructions_per_skill: 1200, block: 4000 };

/** `POST /cluster/agents/skills-preview`: the deploy's own account of the chosen skills. */
export interface SkillsPreview {
  scopes: string[];
  guidance: SkillGuidanceRow[];
  refusals: SkillRefusal[];
  limits: SkillLimits;
}

function asStrings(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
}

function asCount(value: unknown, fallback: number): number {
  return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : fallback;
}

function normalizeGuidance(value: unknown): SkillGuidanceRow {
  const record = asRecord(value);
  const status = asString(record.status);
  return {
    skill_id: asString(record.skill_id),
    name: asString(record.name),
    // A word this console does not know is treated as not sent: the scopes a
    // skill grants are only claimed for a reading that says it was sent.
    status: status === "sent" || status === "shortened" ? status : "not-sent",
    reason: asString(record.reason),
    sent_chars: asCount(record.sent_chars, 0),
    total_chars: asCount(record.total_chars, 0),
    scopes: asStrings(record.scopes),
  };
}

export function normalizeSkillsPreview(value: unknown): SkillsPreview {
  const record = asRecord(value);
  const limits = asRecord(record.limits);
  return {
    scopes: asStrings(record.scopes),
    guidance: Array.isArray(record.guidance) ? record.guidance.map(normalizeGuidance) : [],
    refusals: Array.isArray(record.refusals)
      ? record.refusals.map((item) => {
        const refusal = asRecord(item);
        return { skill_id: asString(refusal.skill_id), reason: asString(refusal.reason) };
      })
      : [],
    limits: {
      skills: asCount(limits.skills, DEFAULT_SKILL_LIMITS.skills),
      instructions_per_skill: asCount(limits.instructions_per_skill, DEFAULT_SKILL_LIMITS.instructions_per_skill),
      block: asCount(limits.block, DEFAULT_SKILL_LIMITS.block),
    },
  };
}

/** Ask the controller what the chosen skills will grant and send (operator, CSRF). */
export async function previewAgentSkills(
  skillIds: string[],
  csrfToken: string,
  signal?: AbortSignal,
): Promise<SkillsPreview> {
  const surface = await apiRequest<unknown>(
    "/cluster/agents/skills-preview",
    { method: "POST", body: JSON.stringify({ skills: skillIds }), cache: "no-store", signal },
    csrfToken,
  );
  return normalizeSkillsPreview(surface);
}
